import gradio as gr
from vertexai.preview.language_models import (ChatModel, InputOutputTextPair,
                                              TextEmbeddingModel,
                                              TextGenerationModel)

def qna(question):
    generation_model = TextGenerationModel.from_pretrained("text-bison@001")
    response = generation_model.predict(
        prompt=question,
        temperature=0.0,
        max_output_tokens=1024
    )
    return response.text, 'query placeholder'

with gr.Blocks() as demo:
    gr.Markdown(
    """
    ## Ask TWN

    ### Sample Inputs:
    1. Suggest 5 activities for people in Toronto this week

    ### Enter a search query...

    """)
    with gr.Row():
      with gr.Column():
        input_text = gr.Textbox(label="Question", placeholder="Suggest 5 activities for people in Toronto this week")

    with gr.Row():
      generate = gr.Button("Ask TWN")

    with gr.Row():
      label2 = gr.Textbox(label="Output")
    with gr.Row():
      label3 = gr.Textbox(label="query generated by LLM")

    generate.click(qna,input_text, [label2, label3])
demo.launch(share=True, debug=False)
